-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 15:44:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema train_station
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema train_station
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `train_station` DEFAULT CHARACTER SET utf8 ;
USE `train_station` ;

-- -----------------------------------------------------
-- Table `train_station`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`country` (
  `id_country` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_country`),
  UNIQUE INDEX `country_UNIQUE` (`country` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`city` (
  `id_city` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `country` INT NOT NULL,
  PRIMARY KEY (`id_city`),
  UNIQUE INDEX `city_UNIQUE` (`city` ASC),
  INDEX `country_idx` (`country` ASC),
  CONSTRAINT `country`
    FOREIGN KEY (`country`)
    REFERENCES `train_station`.`country` (`id_country`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`station` (
  `id_station` INT NOT NULL AUTO_INCREMENT,
  `station` VARCHAR(45) NOT NULL,
  `city` INT NOT NULL,
  PRIMARY KEY (`id_station`),
  UNIQUE INDEX `station_UNIQUE` (`station` ASC),
  INDEX `city_idx` (`city` ASC),
  CONSTRAINT `city`
    FOREIGN KEY (`city`)
    REFERENCES `train_station`.`city` (`id_city`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`task` (
  `id_task` INT NOT NULL AUTO_INCREMENT,
  `task_creator` INT NOT NULL,
  `date_of_creation` DATE NOT NULL,
  `task_name` VARCHAR(45) NOT NULL,
  `task_code` VARCHAR(45) NOT NULL,
  `description` TEXT(200) NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id_task`),
  UNIQUE INDEX `task_code_UNIQUE` (`task_code` ASC),
  INDEX `status_idx` (`status` ASC),
  INDEX `task_creartor_idx` (`task_creator` ASC),
  CONSTRAINT `status`
    FOREIGN KEY (`status`)
    REFERENCES `train_station`.`status` (`id_status`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `task_creartor`
    FOREIGN KEY (`task_creator`)
    REFERENCES `train_station`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`train_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`train_model` (
  `id_train_model` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_train_model`),
  UNIQUE INDEX `model_UNIQUE` (`model` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`train` (
  `id_train` INT NOT NULL AUTO_INCREMENT,
  `model` INT NOT NULL,
  `date_of_creation` DATE NOT NULL,
  PRIMARY KEY (`id_train`),
  INDEX `model_idx` (`model` ASC),
  CONSTRAINT `model`
    FOREIGN KEY (`model`)
    REFERENCES `train_station`.`train_model` (`id_train_model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`trip` (
  `id_trip` INT NOT NULL AUTO_INCREMENT,
  `station` INT NOT NULL,
  `train` INT NOT NULL,
  PRIMARY KEY (`id_trip`),
  INDEX `station_idx` (`station` ASC),
  INDEX `train_idx` (`train` ASC),
  CONSTRAINT `station`
    FOREIGN KEY (`station`)
    REFERENCES `train_station`.`station` (`id_station`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `train`
    FOREIGN KEY (`train`)
    REFERENCES `train_station`.`train` (`id_train`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`alternative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`alternative` (
  `id_alternative` INT NOT NULL AUTO_INCREMENT,
  `trip` INT NOT NULL,
  `task` INT NOT NULL,
  PRIMARY KEY (`id_alternative`),
  INDEX `task_idx` (`task` ASC),
  INDEX `trip_idx` (`trip` ASC),
  CONSTRAINT `task`
    FOREIGN KEY (`task`)
    REFERENCES `train_station`.`task` (`id_task`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `trip`
    FOREIGN KEY (`trip`)
    REFERENCES `train_station`.`trip` (`id_trip`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`rating` (
  `id_rating` INT NOT NULL AUTO_INCREMENT,
  `alternative1` INT NOT NULL,
  `alternative2` INT NOT NULL,
  `expert` INT NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`id_rating`),
  INDEX `alternative1_idx` (`alternative1` ASC),
  INDEX `alternative2_idx` (`alternative2` ASC),
  INDEX `expert_idx` (`expert` ASC),
  CONSTRAINT `alternative1`
    FOREIGN KEY (`alternative1`)
    REFERENCES `train_station`.`alternative` (`id_alternative`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `alternative2`
    FOREIGN KEY (`alternative2`)
    REFERENCES `train_station`.`alternative` (`id_alternative`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `expert`
    FOREIGN KEY (`expert`)
    REFERENCES `train_station`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT(100) NOT NULL,
  `place` INT NOT NULL,
  `time_of_creation` DATETIME NOT NULL,
  `owner` INT NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `place_idx` (`place` ASC),
  INDEX `owner_idx` (`owner` ASC),
  CONSTRAINT `place`
    FOREIGN KEY (`place`)
    REFERENCES `train_station`.`task` (`id_task`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `owner`
    FOREIGN KEY (`owner`)
    REFERENCES `train_station`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`message` (
  `id_message` INT NOT NULL AUTO_INCREMENT,
  `sender` INT NOT NULL,
  `recipient` INT NOT NULL,
  `message` TEXT(150) NOT NULL,
  `time_of_creation` DATETIME NOT NULL,
  PRIMARY KEY (`id_message`),
  INDEX `recepient_idx` (`recipient` ASC),
  INDEX `sender_idx` (`sender` ASC),
  CONSTRAINT `sender`
    FOREIGN KEY (`sender`)
    REFERENCES `train_station`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `recepient`
    FOREIGN KEY (`recipient`)
    REFERENCES `train_station`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`user_roles` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_roles_role1_idx` (`role_id` ASC),
  INDEX `fk_user_roles_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_roles_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `train_station`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_roles_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `train_station`.`role` (`id_role`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_station`.`user_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station`.`user_tasks` (
  `user_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `task_id`),
  INDEX `fk_user_tasks_task1_idx` (`task_id` ASC),
  INDEX `fk_user_tasks_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_tasks_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `train_station`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_tasks_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `train_station`.`task` (`id_task`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
